import { action, computed, flow, makeObservable, observable } from 'mobx';
import { toFlowGeneratorFunction } from 'to-flow-generator-function';

import { type ApiConfig, type ApiType } from '../types/ApiType';
import { callApi } from '../utils/api';
import type { ApiMethodArgs, ApiMethodName } from '../utils/api/types/ApiMethod.type';
import { actionBoundCompat } from '../utils/mobx/actionBoundCompat';
import { LoadingStore } from './LoadingStore';

/**
 * Options for {@link ApiStore.apiCall}.
 * @property {boolean} [disableLoading=false] - When true, the call does not toggle
 *           the store loading flag (useful for background prefetch).
 */
export type ApiCallOptions = {
  disableLoading?: boolean;
};

/**
 * @class ApiStore
 * @template TApi - The type of the generated API client (e.g., PetApi from openapi-generator).
 * @template TConfig - The configuration type required by the TApi client constructor.
 * @description Base store for managing an API client instance and making API calls.
 * It extends `LoadingStore` to provide loading state indicators during API interactions.
 *
 * This store provides two ways to initialize the API client:
 * 1. Pass a `createApi` function in the constructor options
 * 2. Override the `initApi` method in a subclass
 *
 * Endpoint typing uses distributive {@link ApiMethodName} / {@link ApiMethodArgs}
 * helpers so unioned OpenAPI clients expose method keys correctly.
 *
 * @extends LoadingStore
 *
 * @property {TApi | null} api - The observable API client instance. Null until `initApi` is successfully called.
 * @property {boolean} apiIsSet - A computed property that returns true if the API client has been initialized.
 * @property {string} name - The name of the store instance (used for logging and debugging).
 *
 * @method setApi - Action to set the API client instance.
 * @method initApi - Initializes the API client. Can be overridden by subclasses or uses the `createApi` function if provided.
 * @method apiCall - A MobX flow-wrapped method for making generic API calls using the initialized API client.
 *
 * @example
 * // Using createApi function (recommended for simple cases)
 * const myApiStore = new ApiStore({
 *   name: 'MyApiStore',
 *   createApi: (config) => new MyGeneratedApi(config)
 * });
 *
 * @example
 * // Assume MyGeneratedApi is a class generated by OpenAPI generator
 * // and MyApiConfig is its configuration type.
 * // Extending with custom initApi (recommended for complex initialization)
 * class MySpecificApiStore extends ApiStore<MyGeneratedApi, MyApiConfig> {
 *   constructor(name: string) {
 *     super(name);
 *     makeObservable(this, { initApi: override }); // Important for MobX
 *   }
 *
 *   initApi(config: MyApiConfig) {
 *     this.setApi(new MyGeneratedApi(config));
 *   }
 *
 *   async fetchSomeData(id: string) {
 *     // 'someEndpoint' would be a method key on MyGeneratedApi
 *     // The arguments { id } would match the parameters of MyGeneratedApi.someEndpoint
 *     return await this.apiCall('someEndpoint', { id });
 *   }
 * }
 *
 * @example
 * // Backwards compatible usage
 * class LegacyApiStore extends ApiStore<MyApi> {
 *   constructor() {
 *     super('LegacyApiStore'); // Old signature still works
 *   }
 * }
 */
export class ApiStore<
  TApi extends ApiType,
  TConfig extends ApiConfig<TApi> = ApiConfig<TApi>,
> extends LoadingStore {
  /**
   * @property {TApi | null} api
   * @description The observable API client instance. It is `null` until `initApi` is successfully called and `setApi` populates it.
   *              Used by `apiCall` to execute requests.
   * @observable
   */
  api: TApi | null = null;

  /**
   * @property {((config: TConfig) => TApi) | null} createApi
   * @description Optional factory function to create the API client instance.
   *              If provided, it will be used by the default `initApi` implementation.
   * @private
   */
  private createApi: ((config: TConfig) => TApi) | null = null;

  /**
   * @property {string} name
   * @description The name of the store instance, used for logging and debugging.
   *              Defaults to the class name if not provided.
   */
  name: string;

  /**
   * @constructor
   * @description Creates a new ApiStore instance. Supports both legacy and new constructor signatures for backwards compatibility.
   * @param {string | { name?: string; createApi?: (config: TConfig) => TApi }} [nameOrOptions]
   *        - Legacy: A string representing the store name
   *        - New: An options object with optional name and createApi function
   *
   * @example
   * // Legacy signature (backwards compatible)
   * const store1 = new ApiStore('MyStore');
   *
   * @example
   * // New signature with name only
   * const store2 = new ApiStore({ name: 'MyStore' });
   *
   * @example
   * // New signature with createApi function
   * const store3 = new ApiStore({
   *   name: 'MyStore',
   *   createApi: (config) => new MyApi(config)
   * });
   *
   * @example
   * // Minimal usage (name will default to class name)
   * const store4 = new ApiStore();
   */
  constructor(
    nameOrOptions?: string | { name?: string; createApi?: (config: TConfig) => TApi },
  ) {
    super();

    // Handle backwards compatibility and flexible constructor signatures
    if (typeof nameOrOptions === 'string') {
      // Legacy signature: constructor(name: string)
      this.name = nameOrOptions;
      this.createApi = null;
    } else if (nameOrOptions && typeof nameOrOptions === 'object') {
      // New signature: constructor({ name?, createApi? })
      this.name = nameOrOptions.name ?? this.constructor.name;
      this.createApi = nameOrOptions.createApi ?? null;
    } else {
      // No arguments provided
      this.name = this.constructor.name;
      this.createApi = null;
    }

    makeObservable(this, {
      // Prefer bound actions (MobX 6: action.bound, MobX 7: actionBound) so
      // prototype methods keep `this` when used as callbacks.
      initApi: actionBoundCompat,
      setApi: action,
      apiIsSet: computed,
      api: observable,
      name: false,
      apiCall: flow,
    });

    // Typically starts loading until config arrives / initApi runs.
    this.setIsLoading(true);
  }

  /**
   * @method setApi
   * @description Sets the API client instance for the store. Typically called from within `initApi`.
   *              Also clears the loading flag after the client is attached.
   * @param {TApi} api - The API client instance.
   * @action
   */
  setApi = (api: TApi) => {
    this.api = api;
    this.setIsLoading(false);
  };

  /**
   * @method initApi
   * @description Initializes the API client. This method can be implemented in two ways:
   *              1. If a `createApi` function was provided in the constructor, it will be used automatically
   *              2. Override this method in subclasses for custom initialization logic
   * @param {TConfig} config - The configuration object required by the API client (e.g., base path, middleware).
   * @throws {Error} If neither `createApi` function was provided nor the method was overridden by a subclass.
   * @action bound
   */
  initApi(config: TConfig) {
    if (this.createApi) {
      this.setApi(this.createApi(config));
    } else {
      throw new Error(
        `initApi is not implemented for ${this.name}. Either provide a 'createApi' function in the constructor options or override the 'initApi' method in your subclass.`,
      );
    }
  }

  /**
   * @property apiIsSet
   * @description Computed property that checks if the API client has been initialized.
   * @returns {boolean} True if `this.api` is not null, false otherwise.
   * @computed
   */
  get apiIsSet() {
    return this.api !== null;
  }

  /**
   * @method apiCall
   * @template Api - The API client type used for this specific call. Defaults to `TApi`.
   * @template Endpoint - A method name of `Api` (via {@link ApiMethodName}).
   * @template Args - The argument type for `Endpoint` (via {@link ApiMethodArgs}).
   * @description A MobX flow-wrapped method for making generic API calls using the initialized API client (`this.api`).
   *              It automatically handles setting the store's loading state before and after the call unless
   *              `disableLoading` is set. Invokes generated methods with `.call` so `this` stays bound.
   *
   * When TypeScript struggles with the base generic across many subclasses, re-bind a typed
   * `apiCall` wrapper in the subclass that delegates here.
   * @param {Endpoint} endpoint - The name of the API method to call.
   * @param {Args} args - The arguments to pass to the API method.
   * @param {ApiCallOptions} [options] - Optional call options (e.g. `disableLoading`).
   * @returns {Promise<unknown>} A promise that resolves with the result of the API call.
   * @throws {Error} If the API client (`this.api`) has not been initialized.
   * @flow
   */
  apiCall = flow(
    toFlowGeneratorFunction(
      async <
        Api extends ApiType = TApi,
        Endpoint extends ApiMethodName<Api> = ApiMethodName<Api>,
        Args extends ApiMethodArgs<Api, Endpoint> = ApiMethodArgs<Api, Endpoint>,
      >(
        endpoint: Endpoint,
        args: Args extends undefined ? never : Args,
        { disableLoading = false }: ApiCallOptions = {},
      ) => {
        try {
          if (!this.api) throw new Error(`${this.name} Api is not set`);
          if (!disableLoading) this.setIsLoading(true);
          return await callApi<Api, Endpoint, Args>(
            endpoint,
            args,
            this.api as unknown as Api,
          );
        } finally {
          if (!disableLoading) this.setIsLoading(false);
        }
      },
    ),
  );
}
